fos_rest:
    disable_csrf_role: ROLE_API
    body_listener:
        enabled: true
#        array_normalizer:
#            service: fos_rest.normalizer.camel_keys_with_leading_underscore
#            forms: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: ^/doc, host: '%host_apis%', priorities: [ json, html, xml ], fallback_format: xml, prefer_extension: true }
            - { path: ^/, host: '%host_apis%', priorities: [ json, html, xml ], fallback_format: json, prefer_extension: true }
    param_fetcher_listener: true
    routing_loader:
       default_format: json
       include_format: true
    view:
        mime_types:
            json: ['application/javascript+jsonp', 'application/json', 'application/json;version=1.0', 'application/json;version=1.1']
        view_response_listener: 'force'
        formats:
            json: true
            xml:  true
            html: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
    versioning:
        enabled: true
        default_version: "%api.version%"
        resolvers:
            query: true # Query parameter: /users?version=v1
            custom_header: true # X-Accept-Version header
            media_type: # Accept header
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'
        guessing_order:
            - query
            - custom_header
            - media_type
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\Security\Core\Exception\AuthenticationException': 401
            'Symfony\Component\Security\Core\Exception\AccessDeniedException' : 403
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Symfony\Component\Security\Core\Exception\AuthenticationException': true
            'Symfony\Component\Security\Core\Exception\AccessDeniedException' : true
            'Doctrine\ORM\OptimisticLockException': true
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    zone:
        - { host: '%host_apis%', path: '^/v1/*' }
        - { host: '%host_apis%', path: '^/v2/*' }
