parameters:
    locale: "en"
    host_app: http://127.0.0.1
    host_apis: apis.%host_app%
    host_oauth: oauth.%host_app%
    pos.default_scope: user
    pos.interne_client: true
    user.mail: user@exemple.com
    api.version:  v1 # current version
    api.versions:  v1|v2 # current version
    knp.doctrine_behaviors.blameable_subscriber.user_entity: App\Entity\User

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Repository,Event,Listener,Util,Tests,EventListener,Validator,Twig}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
        calls:
            - [setContainer, ["@service_container"]]

    App\Security\Provider\UserProvider:
        $em: '@doctrine.orm.entity_manager' 
        
    # Alias API
    papis.repository:
        class: App\Service\Repository
        autowire: false
        public: true
        arguments:
            $doctrine: '@doctrine'
            $translator: '@translator'
            $serializer: '@jms_serializer'
            $defaultLimit:  50
            $defaultPage: 1
            $defaultGroup: 'list'
            $excludes: ['page', 'limit', 'orderBy', 'fields', 'options']
            $blameables: ['createdBy', 'updatedBy', 'deletedBy']
            
    papis.error_factory:
        class: App\Service\ErrorFactory
        autowire: false
        public: true
        arguments:
            $translator: '@translator'